# -*- coding: utf-8 -*-
"""smart_campus.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12P2qQ88EKc-A1w7e_DuY4pOJgOvih9ol
"""

# =========================================================
# SMART CAMPUS INFORMATION SYSTEM
# Mini Project Integration (Lab 1 to Lab 8)
# =========================================================

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# =========================================================
# GLOBAL DATA STORAGE
# =========================================================

students = []
courses = []
student_ids = []

# =========================================================
# MODULE 1
# STUDENT REGISTRATION AND GRADE EVALUATION
# =========================================================

def student_registration():

    print("\n===== STUDENT REGISTRATION =====")

    name = input("Enter student name: ")
    score = float(input("Enter exam score (0-100): "))

    if score >= 90 and score <= 100:
        grade = "A"
        remark = "Excellent"

    elif score >= 75:
        grade = "B"
        remark = "Very Good"

    elif score >= 60:
        grade = "C"
        remark = "Good"

    elif score >= 40:
        grade = "D"
        remark = "Average"

    else:
        grade = "F"
        remark = "Needs Improvement"

    print("\n--- Student Report ---")
    print("Name:", name)
    print("Score:", score)
    print("Grade:", grade)
    print("Performance Remark:", remark)

# =========================================================
# MODULE 2
# COURSE ENROLLMENT MANAGEMENT
# =========================================================

def course_enrollment():

    print("\n===== COURSE ENROLLMENT =====")

    max_courses = 5

    while True:

        if len(courses) >= max_courses:
            print("Maximum course limit reached!")
            break

        course_name = input("Enter course name (or 'done' to finish): ")

        if course_name.lower() == "done":
            break

        credits = input("Enter credit value: ")

        if not credits.isdigit():
            print("Invalid credit value! Skipping entry...")
            continue

        credits = int(credits)

        if credits <= 0:
            print("Credit must be positive! Skipping entry...")
            continue

        courses.append((course_name, credits))

        print(f"Course '{course_name}' with {credits} credits added.\n")

    print("\n--- Enrollment Report ---")

    for course, credit in courses:
        print(f"Course: {course}, Credits: {credit}")

    print("Total courses enrolled:", len(courses))

# =========================================================
# MODULE 3
# STUDENT RECORD MANAGEMENT
# =========================================================

def student_record_management():

    print("\n===== STUDENT RECORD MANAGEMENT =====")

    n = int(input("Enter number of students: "))

    for i in range(n):

        print(f"\nEnter details for Student {i+1}")

        name = input("Enter name: ")
        age = int(input("Enter age: "))

        grades = []

        for j in range(3):
            mark = int(input(f"Enter mark {j+1}: "))
            grades.append(mark)

        student = {
            "name": name,
            "age": age,
            "grades": grades
        }

        students.append(student)

    print("\n=== Student Records ===")

    for student in students:
        print("--------------------------")
        print("Name:", student["name"])
        print("Age:", student["age"])
        print("Grades:", student["grades"])

    # Set Operations

    print("\n===== EVENT PARTICIPATION ANALYSIS =====")

    event_A = {"Priya", "Rahul", "Anita", "Kiran"}
    event_B = {"Rahul", "Anita", "Sneha"}

    common_participants = event_A & event_B
    all_participants = event_A | event_B
    only_event_A = event_A - event_B

    print("Common Participants:", common_participants)
    print("All Participants:", all_participants)
    print("Only Event A Participants:", only_event_A)

# =========================================================
# MODULE 4
# SORTING AND SEARCHING STUDENT IDs
# =========================================================

def sorting_searching():

    print("\n===== SORTING AND SEARCHING =====")

    n = int(input("Enter number of student IDs: "))

    ids = []

    for i in range(n):
        sid = int(input("Enter student ID: "))
        ids.append(sid)

    print("Original IDs:", ids)

    # Bubble Sort

    bubble_sorted = ids.copy()

    for i in range(len(bubble_sorted)):
        for j in range(0, len(bubble_sorted)-i-1):

            if bubble_sorted[j] > bubble_sorted[j+1]:

                temp = bubble_sorted[j]
                bubble_sorted[j] = bubble_sorted[j+1]
                bubble_sorted[j+1] = temp

    print("Sorted IDs (Bubble Sort):", bubble_sorted)

    # Selection Sort

    selection_sorted = ids.copy()

    n = len(selection_sorted)

    for i in range(n):

        min_index = i

        for j in range(i+1, n):

            if selection_sorted[j] < selection_sorted[min_index]:
                min_index = j

        temp = selection_sorted[i]
        selection_sorted[i] = selection_sorted[min_index]
        selection_sorted[min_index] = temp

    print("Sorted IDs (Selection Sort):", selection_sorted)

    # Linear Search

    target = int(input("Enter ID to search: "))

    found = -1

    for i in range(len(bubble_sorted)):

        if bubble_sorted[i] == target:
            found = i
            break

    if found != -1:
        print("Linear Search: ID found at index", found)
    else:
        print("Linear Search: ID not found")

    # Binary Search

    low = 0
    high = len(bubble_sorted) - 1
    found = -1

    while low <= high:

        mid = (low + high) // 2

        if bubble_sorted[mid] == target:
            found = mid
            break

        elif bubble_sorted[mid] < target:
            low = mid + 1

        else:
            high = mid - 1

    if found != -1:
        print("Binary Search: ID found at index", found)
    else:
        print("Binary Search: ID not found")

# =========================================================
# MODULE 5
# FEE CALCULATION USING FUNCTIONS
# =========================================================

def calculate_fee(tuition_fee, hostel_fee=0, transportation_fee=0):

    total_fee = tuition_fee + hostel_fee + transportation_fee

    return total_fee

def fee_management():

    print("\n===== FEE CALCULATION =====")

    tuition = float(input("Enter tuition fee: "))
    hostel = float(input("Enter hostel fee: "))
    transport = float(input("Enter transportation fee: "))

    total = calculate_fee(tuition, hostel, transport)

    print("Total Fee:", total)

# =========================================================
# MODULE 6
# FILE HANDLING FOR STUDENT RECORDS
# =========================================================

def file_handling():

    print("\n===== FILE HANDLING =====")

    with open("student_records.txt", "w") as file:

        file.write("ID,Name,Marks\n")
        file.write("101,Arjun,85\n")
        file.write("102,Meera,92\n")
        file.write("103,Ravi,76\n")
        file.write("104,Anita,89\n")

    print("Student records written successfully.")

    print("\nReading records:")

    with open("student_records.txt", "r") as file:

        records = file.readlines()

        for record in records:
            print(record.strip())

    print("\nGenerating Report:")

    total_students = 0
    total_marks = 0
    highest_marks = -1
    top_student = ""

    for record in records[1:]:

        parts = record.strip().split(",")

        name = parts[1]
        marks = int(parts[2])

        total_students += 1
        total_marks += marks

        if marks > highest_marks:
            highest_marks = marks
            top_student = name

    average_marks = total_marks / total_students

    print("Total Students:", total_students)
    print("Average Marks:", average_marks)
    print("Top Student:", top_student)
    print("Highest Marks:", highest_marks)

# =========================================================
# MODULE 7
# DIRECTORY SCANNING WITH EXCEPTION HANDLING
# =========================================================

class MissingFileOrFolderError(Exception):
    pass

def scan_directory(path):

    try:

        if not os.path.exists(path):
            raise FileNotFoundError("Invalid directory path!")

        print("\nScanning Directory:\n")

        for root, dirs, files in os.walk(path):

            level = root.replace(path, "").count(os.sep)

            indent = " " * 4 * level

            print(f"{indent}{os.path.basename(root)}/")

            sub_indent = " " * 4 * (level + 1)

            for f in files:
                print(f"{sub_indent}{f}")

            if not files and not dirs:
                raise MissingFileOrFolderError(
                    f"Empty folder detected: {root}"
                )

    except FileNotFoundError as e:
        print("Error:", e)

    except MissingFileOrFolderError as e:
        print("Custom Error:", e)

    except Exception as e:
        print("Unexpected Error:", e)

def directory_module():

    print("\n===== DIRECTORY SCANNING =====")

    path = input("Enter directory path: ")

    scan_directory(path)

# =========================================================
# MODULE 8
# PERFORMANCE ANALYSIS USING NUMPY, PANDAS, MATPLOTLIB
# =========================================================

def performance_analysis():

    print("\n===== PERFORMANCE ANALYSIS =====")

    try:

        df = pd.read_csv("student_performance.csv")

        print("\n--- Raw Data ---")
        print(df.head())

        print("\n--- Statistical Summary ---")
        print(df.describe())

        scores = df[["Math", "Science", "English"]].to_numpy()

        mean_scores = np.mean(scores, axis=0)
        median_scores = np.median(scores, axis=0)
        std_scores = np.std(scores, axis=0)

        print("\n--- NumPy Analysis ---")

        print("Mean Scores:", mean_scores)
        print("Median Scores:", median_scores)
        print("Standard Deviation:", std_scores)

        top_math = df.loc[df["Math"].idxmax(), "Name"]
        top_science = df.loc[df["Science"].idxmax(), "Name"]
        top_english = df.loc[df["English"].idxmax(), "Name"]

        print("\n--- Top Performers ---")

        print("Math:", top_math)
        print("Science:", top_science)
        print("English:", top_english)

        # Graph 1

        subjects = ["Math", "Science", "English"]

        plt.bar(subjects, mean_scores)

        plt.title("Average Scores per Subject")
        plt.xlabel("Subjects")
        plt.ylabel("Average Score")

        plt.show()

        # Graph 2

        df.plot(
            x="Name",
            y=["Math", "Science", "English"],
            kind="bar"
        )

        plt.title("Student Performance Comparison")
        plt.ylabel("Scores")

        plt.show()

    except FileNotFoundError:
        print("CSV file not found!")

    except Exception as e:
        print("Unexpected Error:", e)

# =========================================================
# MAIN MENU
# =========================================================

while True:

    print("\n")
    print("=================================================")
    print(" SMART CAMPUS INFORMATION SYSTEM ")
    print("=================================================")

    print("1. Student Registration and Grade Evaluation")
    print("2. Course Enrollment Management")
    print("3. Student Record Management")
    print("4. Sorting and Searching Student IDs")
    print("5. Student Fee Calculation")
    print("6. File Handling for Academic Records")
    print("7. Directory Scanning")
    print("8. Student Performance Analysis")
    print("9. Exit")

    choice = input("Enter your choice: ")

    if choice == "1":
        student_registration()

    elif choice == "2":
        course_enrollment()

    elif choice == "3":
        student_record_management()

    elif choice == "4":
        sorting_searching()

    elif choice == "5":
        fee_management()

    elif choice == "6":
        file_handling()

    elif choice == "7":
        directory_module()

    elif choice == "8":
        performance_analysis()

    elif choice == "9":
        print("Exiting Smart Campus Information System...")
        break

    else:
        print("Invalid choice! Please try again.")

